// cli_transport_usart2.c — USART2 / RS232 transport for TimbreOS CLI
//
// USART2 connects to the RS232 port on the extender board and is the
// default CLI transport — active from boot, no connection handshake needed.
//
// Input routing:
//   Before each keyIn() call, EmitEvent is pointed at usart2_emit so that
//   output is automatically directed back to RS232.
//   autoEchoOff() is used — the RS232 terminal expects the device to echo.
//
// TX is interrupt-driven.  usart2_emit() (the EmitEvent target) enables the
// TXE interrupt to kick off transmission; usart2_tx_irq() drains emitq one
// byte per TXE interrupt.  When the queue empties, TXE is disabled and the TC
// interrupt is armed to detect when the last byte has fully shifted out.
//
// RX uses the RXNE interrupt.  The single-instance state machine
// (IDLE → QUEUED → RUNNING → REQUEUE) prevents queue overflow if bytes
// arrive faster than the action runs.
//
// Required wiring in stm32f4xx_it.c USART2_IRQHandler:
//   usart2_rx_irq() — when RXNE flag set and RXNE interrupt enabled
//   usart2_tx_irq() — when TXE  flag set and TXE  interrupt enabled
//   usart2_tc_irq() — when TC   flag set and TC   interrupt enabled

#include <stdint.h>
#include <stdbool.h>

#include "stm32f4xx_ll_usart.h"

#include "tea.h"
#include "cli.h"
#include "byteq.h"
#include "printers.h"

#include "cli_transport_usart2.h"

// ── Forward declaration ───────────────────────────────────────────────────────

static void usart2_rx_action(void);

// ── EmitEvent target — kicks off interrupt-driven TX ─────────────────────────
//
// Called cooperatively from the action queue.  If the TXE interrupt is already
// running (transmission in progress) the new bytes in emitq will be drained
// automatically — no action needed.  Otherwise enable TXE to start the ISR
// drain loop.

static void usart2_emit(void) {
    if (qbq(emitq))
        LL_USART_EnableIT_TXE(USART2);
}

// ── usart2_tx_irq — call from USART2_IRQHandler when TXE flag + IT active ────
//
// Sends one byte per interrupt.  When the queue drains: disables TXE and arms
// TC so we know when the last byte has fully shifted out of the shift register.

void usart2_tx_irq(void) {
    if (qbq(emitq)) {
        LL_USART_TransmitData8(USART2, pullbq(emitq));
    } else {
        LL_USART_DisableIT_TXE(USART2);
        LL_USART_EnableIT_TC(USART2);
    }
}

// ── usart2_tc_irq — call from USART2_IRQHandler when TC flag + IT active ─────
//
// Fires once the shift register drains after the last byte.  Disables TC to
// avoid spurious interrupts; clears the flag so the next transmission starts
// cleanly.

void usart2_tc_irq(void) {
    LL_USART_DisableIT_TC(USART2);
    LL_USART_ClearFlag_TC(USART2);
}

// ── usart2_rx_irq — call from USART2_IRQHandler ───────────────────────────────
static BQUEUE(100, cliq);

void usart2_rx_irq(void) {
    pushbq(LL_USART_ReceiveData8(USART2), cliq);
    if (qbq(cliq) == 1)
        later(usart2_rx_action);
}

// ── usart2_rx_action — tea.c action, single-instance ─────────────────────────

static void usart2_rx_action(void) {
    // rx_state = USART2_RUNNING;

    // Direct output back to RS232 before processing any characters.
    when(EmitEvent, usart2_emit);
    autoEchoOff();       // RS232 terminal expects device-side echo

    while (qbq(cliq))  keyIn(pullbq(cliq));
    safe( if(qbq(cliq)) later(usart2_rx_action); )
    // safely interlock the state machine to prevent orphan bytes
}

// ── usart2_transport_init — call once from board init ────────────────────────

void usart2_transport_init(void) {
    // Enable USART2 RXNE interrupt — USART2 peripheral itself is already
    // initialised by MX_USART2_UART_Init() generated by CubeMX.
    LL_USART_EnableIT_RXNE(USART2);

    // Establish USART2 as the default CLI transport from boot.
    when(EmitEvent, usart2_emit);
    autoEchoOff();
}

// irq handler
void usart2_irq() {
    if (LL_USART_IsActiveFlag_RXNE(USART2) && LL_USART_IsEnabledIT_RXNE(USART2))
        usart2_rx_irq();
    if (LL_USART_IsActiveFlag_TXE(USART2)  && LL_USART_IsEnabledIT_TXE(USART2))
        usart2_tx_irq();
    if (LL_USART_IsActiveFlag_TC(USART2)   && LL_USART_IsEnabledIT_TC(USART2))
        usart2_tc_irq();
}

